#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 13 07:53:05 2018

@author: agb
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style('white')
plt.style.use('ggplot')



#%% data importing

train_df = pd.read_csv("../data/train.csv",header=0)
test_df = pd.read_csv("../data/test.csv",header=0)

#%%  simple survival split for male vs female

print("\n")
print("# survivors by sex:")
print(pd.crosstab(train_df['Sex'],train_df['Survived'],margins=True))

print("\n")
print("Survival rate by sex:")
print(pd.crosstab(train_df['Sex'],train_df['Survived'],normalize='index').xs(1,axis=1))

m_surv_rate = pd.crosstab(train_df['Sex'],train_df['Survived'],normalize='index').xs(1,axis=1)['male']
f_surv_rate = pd.crosstab(train_df['Sex'],train_df['Survived'],normalize='index').xs(1,axis=1)['female']

print("\n")
print("Difference in survival rates (women - men):")
print('%.4f' % (f_surv_rate - m_surv_rate))

#%%  Hypothesis testing using Randomisation Simulation

'''H<sub>0</sub>:  The variables `Sex` and `Survival` are independent.
They have no relationship, and the observed difference between the proportion 
of males and females who survived the sinking of the Titanic (55.31%) 
was due to chance.

H<sub>1</sub>: The variables `Sex` and `Survival` are not independent.
The difference in survival rates of 55.31% was not due to chance,
and sex does help predict survival.'''

from sklearn.utils import shuffle

hyp_df = train_df.copy()[['Sex','Survived']]

def calc_surv_rate_diff(sex,survived):
    df = pd.crosstab(sex,survived,normalize='index').xs(1,axis=1)
    surv_diff = df['female'] - df['male']
    return surv_diff

diffs = []
surv = np.array(hyp_df['Survived'])
for i in range(0,10000):
    sex = np.array(shuffle(hyp_df['Sex']))
    new_surv_diff = calc_surv_rate_diff(sex,surv)
    diffs.append(new_surv_diff)

#%% feature engineering - add title column

title_dict = {'male':'Mr.','female':'Mrs.'}

def gen_new_features(df):
    titles = []
    lastnames = []
    for idx, row in df.iterrows():
        # pull out the title first
        title = None
        for s in row['Name'].split()[:2]:
            if "." in s:
                title = s
        if title == None:
            try:
                title = title_dict[row['Sex']]
            except:
                print("Unable to deduce title for:",row['Name'],row['Sex'])
                title = np.nan
        titles.append(title)

        # then pull out the lastname
        lastname = None
        try:
            lastname = row['Name'].split(",")[0]
        except:
            print("Unable to deduce lastname for:",row['Name'])
            lastname = np.nan
        lastnames.append(lastname)
        
    df['eTitle'] = titles
    df['eLastname'] = lastnames

gen_new_features(train_df)

#%%

